---
title: "Visualizing_Corona"
output: html_document
---

```{r}
library(pacman)
p_load(remotes,tidyverse, ggplot, gganimate)
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
remotes::install_github("sebastianbarfort/mapDK")
library(mapDK)



df <- read.csv2("corona2511/Municipality_cases_time_series.csv")

data_long <- gather(df, kommune, pos_test, Roskilde:Samsø, factor_key=TRUE)


kommune_df <- read.csv2("corona2511/Municipality_test_pos.csv",sep=";")
names(kommune_df)[2] <- "kommune"
kommune_df$Befolkningstal <- as.character(as.factor(kommune_df$Befolkningstal))
kommune_df$Befolkningstal <- str_remove_all(kommune_df$Befolkningstal, "\\.")
kommune_df$Befolkningstal <- as.numeric(kommune_df$Befolkningstal)

data_long$kommune <- as.character(data_long$kommune)
data_long$kommune <- ifelse(data_long$kommune=="Copenhagen", "København", data_long$kommune)
kommune_df$kommune <- gsub("-", ".", kommune_df$kommune)

data_long <- left_join(data_long, kommune_df, by="kommune")

data_long <- data_long %>% select(c(date_sample, kommune, pos_test, Befolkningstal))


data_long$weekcum <- 0
datoer <- sort(levels(as.factor(data_long$date_sample)))
sen <- datoer[-c(1:7)]

for(i in 1:nrow(data_long)){
  if(data_long$date_sample[i] %in% sen){
    print(i)
    
    data_long$weekcum[i] <- sum(data_long[data_long$kommune==data_long$kommune[i]& 
                                            data_long$date_sample %in%datoer[(which(datoer==data_long$date_sample[i])-6):which(datoer==data_long$date_sample[i])],]$pos_test)
  }
}

data_long$prhund_week <- (data_long$weekcum/data_long$Befolkningstal)*100000

data_long$kommune <- tolower(data_long$kommune)
data_long$kommune <- gsub("\\.", "", data_long$kommune)
data_long$kommune <- gsub("æ", "ae", data_long$kommune)
data_long$kommune <- gsub("ø", "oe", data_long$kommune)

b <- datoer[-c(1:3)][seq(1, length(datoer[-c(1:3)]), 7)]
sundays <- data_long[data_long$date_sample %in% b,]


all <- data.frame()

sundays$date_sample <- factor(sundays$date_sample)


for(w in levels(sundays$date_sample)){
  animation <- sundays[sundays$date_sample == w,] %>%
    mapDK(values = "prhund_week", id = "kommune",
                                 data = .)
  a <- as.data.frame(((animation$data)))
  a$date_sample <- w
  all <- rbind(all, a)

  
}
p_load(calendR)


animation <- sundays[sundays$date_sample=="2020-09-06",] %>%
    mapDK(values = "prhund_week", id = "kommune",data = .)+
  scale_fill_gradientn(colours = c("#DDEDC9", "#ff6700", "#f40f2a"))+labs(fill = "Cases per 100.000")+theme(plot.title = element_text(size=15))

#scale_fill_gradient2(low = "#50BB44", mid ="#F7C6C5",  high = "#f40f2a")
animation$data <- all

kommune_ani <- animation+transition_states(date_sample)+
        labs(title='Positive tests per. 100.000 in week leading up to {closest_state}',
caption='Source: SSI.dk')

animation <- animate(kommune_ani, nframes = 300, fps = 10 ,width = 1200, height = 900)

anim_save("danmark_blue.gif", animation)
```

```{r}
p_load(lubridate)

df_tests <- read.csv2("corona2511/Municipality_tested_persons_time_series.csv")
all_tests <- df_tests %>%
    mutate(Total = select(., Copenhagen:Aalborg) %>% rowSums(na.rm = TRUE)) %>%
  select(PrDate_adjusted, Total)

names(all_tests)[1] <- "date_sample"

prdag <- data_long %>% group_by(date_sample) %>% summarise(cases = sum(pos_test))
prdag <- left_join(prdag, all_tests)
prdag$pos_procent <- (prdag$cases/prdag$Total)*100

prdag <- prdag[-length(prdag),]
line <- ggplot(prdag, aes(x = ymd(date_sample), y = cases)) + geom_point(colour = "red") + geom_line(colour = "red")+ geom_line(mapping = aes(x = ymd(date_sample), y = 50*pos_procent))+
  ylim(0,1400)+ xlim(ymd("2020-02-26"), ymd("2020-11-06"))+
  geom_text(x = ymd("2020-04-30"), y=1300, label ="Percentage positive tests x 50",size = 15)+
  geom_text(x = ymd("2020-04-03"), y=1375, label ="Total cases", colour="red",size = 15)+
  xlab("Date")+ylab("Cases per day")+
  theme(axis.title=element_text(size=20,face="bold"),
                   axis.text=element_text(size=15))+
  theme_bw()+
  transition_reveal(ymd(date_sample))


animation_line <- animate(line, nframes = 300, fps = 10 ,width = 1200, height = 900)
anim_save("lineplot_pos.gif", animation_line)

```

```{r}

events <- as.data.frame(events)
c <- events %>% calendR(year = 2021,
        start = "M",
        special.days = events,
        special.col = "#bfe2f2",
        low.col = "white") +transition_states(date)

events <- c(1:60)
dates <- seq(as.Date("2020-08-01"), as.Date("2020-08-31"), by = "1 day")
events <- ifelse(format(dates, "%w") %in% c(6), "Sunday", NA)

```

